### ISSUE TITLE
Public Bower component

### ISSUE THREAD

**Issue by JulianLaval** [PolymerElements/iron-test-helpers#21]
I just noticed that this component is set to private in `bower.json` - any chance on releasing it publicly?  :)

**Comment by notwaldorf** [comment]
`private:true` just means it isn't published on the bower catalog, but it's still available from `bower` as an install (`bower install polymerelements/iron-test-helpers`). We don't really want to publish it on the catalog since Polymer Elements don't really make sense without Polymer itself, and we've tried to aggregate all of the ones we are officially publishing on our catalog (elements.polymer-project.org)
